name: postman-newman-dockerhub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NOME_IMAGEM: apifinancas-newman
  CAMINHO_PROJETO_WEBAPP: ./APIFinancas
  CAMINHO_TESTES: ./Tests
  NOME_APLICACAO: apifinancas
  AZURE_RESOURCE_GROUP_K8S: TesteKubernetes
  AZURE_CLUSTER_K8S: AKSCluster
  NAMESPACE_K8S: apifinancasgha  

jobs:
  build-tests-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
      
    - name: Build de imagem
      run: |
        cd ${{ env.CAMINHO_PROJETO_WEBAPP }}
        docker build . --file Dockerfile --tag ${{ secrets.AZURECR_REGISTRY }}/${{ env.NOME_IMAGEM }}:latest
        
    - name: Criação de container para testes com a API
      run: |
        docker run --name api-testes -p 1234:80 -d ${{ secrets.AZURECR_REGISTRY }}/${{ env.NOME_IMAGEM }}:latest
        docker container ls

    - name: Configurar porta da API no arquivo com os testes
      run: |
        cd ${{ env.CAMINHO_TESTES }}
        sed -i 's/5000/1234/' CalculoJurosCompostos.postman_collection.json

    - name: Testes da API REST com Newman
      run: |
        mkdir JUnit
        cd ${{ env.CAMINHO_TESTES }}
        echo "** Versão Global do Newman **"
        newman -v
        newman run CalculoJurosCompostos.postman_collection.json -d data-tests.json -r cli,junit
        chmod -R 777 *.xml
        cd ./newman
        ls
        
    - name: Criar Test Summary
      uses: test-summary/action@dist
      env:
        CAMINHO_RESULTADO_TESTES: ${{ env.CAMINHO_TESTES }}/newman/*.xml
      if: always()
      with:
        paths: ${{ env.CAMINHO_RESULTADO_TESTES }}
        
    - name: Testes da API REST com Newman + HTML Report + XML JUnit
      if: always()
      run: |
        cd ${{ env.CAMINHO_TESTES }}
        echo "** Versão Global do Newman **"
        newman -v
        npm install newman-reporter-htmlextra@1.22.9
        npx newman run CalculoJurosCompostos.postman_collection.json -d data-tests.json -r htmlextra
        echo "** Arquivos + diretórios gerados **"
        cd newman
        ls

    - name: Upload como Artifact do Report com resultado dos testes (Postman + Newman)
      uses: actions/upload-artifact@v2.2.3
      env:
        CAMINHO_RESULTADO_TESTES: ${{ env.CAMINHO_TESTES }}/newman/
      if: always()
      with:
        name: resultado-testes
        path: ${{ env.CAMINHO_RESULTADO_TESTES }}
        retention-days: 30
